
BetterBlizzFramesDB = {
["targetAbsorbIcon"] = true,
["frameAurasXPos"] = 0,
["maxTargetDebuffs"] = 16,
["racialIndicatorOrc"] = true,
["hidePlayerLeaderIcon"] = true,
["targetCastBarWidth"] = 150,
["petCastBarWidth"] = 103,
["darkModeUi"] = true,
["targetAndFocusAuraScale"] = 1,
["focusdeBuffFilterBlizzard"] = true,
["targetdeBuffFilterBlizzard"] = true,
["petCastBarScale"] = 1,
["castBarInterruptHighlighterStartPercentage"] = 15,
["focusCastbarIconYPos"] = 0,
["hidePlayerCornerIcon"] = true,
["targetAbsorbAnchor"] = "TOP",
["classColorTargetNames"] = false,
["hideChatButtons"] = false,
["hideTargetReputationColor"] = true,
["racialIndicatorNelf"] = true,
["playerCastBarIconScale"] = 1,
["targetAndFocusAuraOffsetY"] = 0,
["partyCastBarTestMode"] = false,
["updates"] = "1.4.0",
["purgeTextureColorRGB"] = {
0,
0.92,
1,
0.85,
},
["partyCastBarYPos"] = 0,
["racialIndicatorXPos"] = 0,
["focusdeBuffFilterLessMinite"] = false,
["racialIndicatorYPos"] = 0,
["playerCastBarTimer"] = false,
["playerCastbarIconYPos"] = 0,
["targetAndFocusHorizontalGap"] = 3,
["printAuraSpellIds"] = false,
["castBarInterruptHighlighterDontInterruptRGB"] = {
1,
0,
0,
},
["playerAuraSpacingY"] = 0,
["hideCombatIcon"] = true,
["hideTargetToT"] = false,
["targetToTYPos"] = 0,
["targetBuffFilterBlacklist"] = true,
["targetImportantAuraGlow"] = false,
["focusCastbarIconXPos"] = 0,
["filterEmoteSpam"] = false,
["focusToTScale"] = 1,
["PlayerAuraFramedeBuffEnable"] = true,
["castBarRecolorInterrupt"] = false,
["targetCastbarIconYPos"] = 0,
["combatIndicatorShowSap"] = false,
["combatIndicatorYPos"] = 0,
["hideFocusCombatGlow"] = false,
["playerCastBarScale"] = 1,
["focusToTAnchor"] = "BOTTOMRIGHT",
["focusCastBarYPos"] = 0,
["partyCastBarScale"] = 1,
["playerAbsorbAnchor"] = "TOP",
["focusToTAdjustmentOffsetY"] = 0,
["combatIndicatorXPos"] = 0,
["hideMinimap"] = false,
["playerCastBarTimerCenter"] = false,
["auraWhitelistColorsUpdated"] = true,
["targetToTAnchor"] = "BOTTOMRIGHT",
["hideTargetToTName"] = false,
["frameAuraWidthGap"] = 0,
["playerCastBarWidth"] = 208,
["targetBuffFilterPurgeable"] = false,
["targetToTAdjustmentOffsetY"] = 0,
["playerAuraFiltering"] = false,
["reopenOptions"] = false,
["hasSaved"] = true,
["focusCastBarXPos"] = 0,
["focusdeBuffEnable"] = true,
["combatIndicatorScale"] = 1,
["hasCheckedUi"] = true,
["playerFrameOCDTextureBypass"] = true,
["targetToTXPos"] = 0,
["targetCombatIndicator"] = true,
["targetCastBarYPos"] = 0,
["racialIndicator"] = false,
["hideFocusReputationColor"] = true,
["targetPrestigeBadgeAlpha"] = true,
["racialIndicatorScale"] = 1,
["focusCastBarIconScale"] = 1,
["targetBuffFilterOnlyMe"] = false,
["hideRaidFrameManager"] = true,
["onlyPandemicAuraMine"] = true,
["darkModeColor"] = 0.2,
["displayDispelGlowAlways"] = false,
["racialIndicatorUndead"] = true,
["playerdeBuffFilterBlacklist"] = true,
["targetCastBarIconScale"] = 1,
["targetCastBarTimer"] = false,
["hidePlayerName"] = false,
["castBarInterruptHighlighterEndTime"] = 0.6,
["focusBuffFilterBlacklist"] = true,
["maxBuffFrameBuffs"] = 32,
["showHiddenAurasIcon"] = true,
["absorbIndicator"] = false,
["enablePlayerBuffFiltering"] = true,
["stealthIndicatorPlayer"] = false,
["maxDebuffFrameDebuffs"] = 16,
["showPartyCastBarIcon"] = true,
["focusToTXPos"] = 0,
["focusdeBuffFilterWatchList"] = false,
["focusBuffFilterOnlyMe"] = false,
["lossOfControlScale"] = 1,
["petCastbar"] = false,
["focusdeBuffFilterAll"] = false,
["targetdeBuffFilterBlacklist"] = true,
["partyCastBarIconScale"] = 1,
["overShieldsCompact"] = true,
["centerNames"] = false,
["wasOnLoadingScreen"] = false,
["targetAndFocusSmallAuraScale"] = 1,
["compactedAuraSize"] = 0.7,
["hideTargetToTDebuffs"] = true,
["hidePrestigeBadge"] = true,
["playerAuraSpacingX"] = 5,
["partyCastBarTimer"] = false,
["auraToggleIconTexture"] = 134430,
["focusdeBuffFilterOnlyMe"] = false,
["focusBuffFilterWatchList"] = false,
["targetToTCastbarAdjustment"] = true,
["overShields"] = true,
["targetdeBuffPandemicGlow"] = false,
["focusCombatIndicator"] = true,
["focusCastBarScale"] = 1,
["hideLossOfControlFrameLines"] = true,
["showPetCastBarTimer"] = false,
["targetdeBuffFilterLessMinite"] = false,
["partyCastBarHeight"] = 12,
["focusPrestigeBadgeAlpha"] = true,
["focusdeBuffFilterBlacklist"] = true,
["hidePlayerRestAnimation"] = true,
["hidePlayerRoleIcon"] = true,
["playerBuffFilterBlacklist"] = true,
["targetAbsorbYPos"] = 0,
["darkModeUiAura"] = true,
["targetAbsorbAmount"] = true,
["partyCastBarWidth"] = 100,
["focusToTYPos"] = 0,
["targetRacialIndicator"] = true,
["castBarDelayedInterruptColor"] = {
1,
0.4784314036369324,
0.9568628072738647,
},
["petCastBarHeight"] = 10,
["targetBuffFilterWatchList"] = false,
["auraWhitelist"] = {
{
["flags"] = {
["important"] = false,
["enlarged"] = false,
["pandemic"] = false,
},
["entryColors"] = {
["text"] = {
["a"] = 1,
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Example Aura :3 (delete me)",
},
},
["hidePlayerRestGlow"] = true,
["targetBuffFilterAll"] = true,
["targetdeBuffFilterOnlyMe"] = false,
["partyCastbarIconXPos"] = 0,
["focusRacialIndicator"] = true,
["focusAbsorbAmount"] = true,
["PlayerAuraFrameBuffEnable"] = true,
["absorbIndicatorTestMode"] = false,
["targetCastbarIconXPos"] = 0,
["classColorFrames"] = true,
["focusCastBarTimer"] = false,
["hideArenaFrames"] = true,
["removeRealmNames"] = true,
["targetCastBarXPos"] = 0,
["PlayerAuraFrameBuffFilterWatchList"] = false,
["absorbIndicatorScale"] = 1,
["enablePlayerDebuffFiltering"] = false,
["targetAndFocusVerticalGap"] = 4,
["frameAuraRowAmount"] = 0,
["auraTypeGap"] = 4,
["targetToTScale"] = 1,
["targetdeBuffEnable"] = true,
["focusToTCastbarAdjustment"] = true,
["targetCastBarHeight"] = 10,
["playerCastbarIconXPos"] = 0,
["targetdeBuffFilterWatchList"] = false,
["overShieldsUnitFrames"] = true,
["focusBuffFilterPurgeable"] = false,
["hideFocusToTDebuffs"] = true,
["playerAbsorbAmount"] = true,
["showPetCastBarIcon"] = true,
["targetToTXPosXPos"] = 0,
["focusAbsorbIcon"] = true,
["darkModeMinimap"] = true,
["focusImportantAuraGlow"] = false,
["frameAurasYPos"] = 0,
["filterTalentSpam"] = true,
["playerReputationClassColor"] = true,
["filterNpcArenaSpam"] = true,
["partyCastBarXPos"] = 0,
["focusCastBarWidth"] = 150,
["targetAbsorbXPos"] = 0,
["castBarInterruptHighlighterEndPercentage"] = 80,
["PlayerAuraFramedeBuffFilterWatchList"] = false,
["focusCastBarHeight"] = 10,
["playerCastBarHeight"] = 11,
["auraWhitelistAlphaUpdated"] = true,
["maxAurasOnFrame"] = 0,
["maxTargetBuffs"] = 32,
["playerCombatIndicator"] = false,
["castBarInterruptHighlighterStartTime"] = 0.8,
["enlargedAuraSize"] = 1.4,
["petCastBarXPos"] = 0,
["hidePvpTimerText"] = false,
["racialIndicatorHuman"] = true,
["focusBuffFilterAll"] = true,
["playerAbsorbIcon"] = true,
["hideDragonFlying"] = true,
["combatIndicator"] = true,
["playerAbsorbYPos"] = 0,
["playerReputationColor"] = false,
["darkModeCastbars"] = true,
["darkModeActionBars"] = true,
["playerFrameOCD"] = true,
["combatIndicatorShowSwords"] = true,
["petCastBarTestMode"] = false,
["hideGroupIndicator"] = true,
["targetdeBuffFilterAll"] = false,
["hideLevelText"] = false,
["partyCastbarIconYPos"] = 0,
["petCastBarYPos"] = 0,
["focusToTXPosXPos"] = 0,
["targetAndFocusAurasPerRow"] = 6,
["castBarInterruptHighlighterInterruptRGB"] = {
0,
1,
0,
},
["version"] = "1.00",
["frameAuraHeightGap"] = 0,
["auraBlacklist"] = {
{
["name"] = "Sign of the Skirmisher",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
},
{
["name"] = "Sign of the Scourge",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
},
{
["name"] = "Stormwind Champion",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
},
{
["name"] = "Honorless Target",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
},
{
["name"] = "Guild Champion",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
},
{
["name"] = "Sign of Iron",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
},
{
["id"] = 397734,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Word of a Worthy Ally",
},
{
["id"] = 186403,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Sign of Battle",
},
{
["id"] = 282559,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Enlisted",
},
{
["id"] = 32727,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Arena Preparation",
},
{
["id"] = 418563,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "WoW's 19th Anniversary",
},
{
["id"] = 93805,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Ironforge Champion",
},
},
["overShieldsCompactUnitFrames"] = true,
["targetBuffFilterLessMinite"] = false,
["frameAuraScale"] = 0,
["targetAndFocusAuraOffsetX"] = 0,
["hidePlayerPower"] = false,
["castBarNoInterruptColor"] = {
1,
0,
0.01568627543747425,
},
["playerAbsorbXPos"] = 0,
["focusBuffFilterLessMinite"] = false,
["hidePartyFrameTitle"] = true,
["focusdeBuffPandemicGlow"] = false,
["targetBuffEnable"] = true,
["normalCastbarForEmpoweredCasts"] = true,
["combatIndicatorAnchor"] = "RIGHT",
["focusBuffEnable"] = true,
["petCastBarIconScale"] = 1,
["targetCastBarScale"] = 1,
}
